# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BatchSldExport
                                 A QGIS plugin
 export symbology as SLD for each vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-10
        copyright            : (C) 2020 by Nicolas PERREL
        email                : nicolas.perrel@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BatchSldExport class from file BatchSldExport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .batch_sld_export import BatchSldExport
    return BatchSldExport(iface)
